module.exports = {
	apps: [
		{
			name: 'daily-ingestion',
			script: './app.js',
			watch: true,
			env: {
				NODE_ENV: 'PROD',
				NODE_APP_INSTANCE: 'PROD',
				DB_USER: 'svcecmnuxeo',
				DB_PASSWORD: '2DJCRIzlQFsnMZfzTRii3NXJ',
				DB_DATABASE: 'ecmtoolsdb',
				DB_SCHEMA: 'nuxeo',
				DB_PORT: '5432',
				DB_HOST: 'gfusw-pecm301-r0.na.corp.mckesson.com',
				DB_SSL_CA: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-server-ca.pem',
				DB_SSL_KEY: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-client-key.pem',
				DB_SSL_CERT: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-client-cert.pem',
				FP_ROOT: 'D:/DailyIngest',
				NUX_BASE_URL: 'https://ecm.mckesson.com/nuxeo/',
				NUX_USERNAME: 'svcDailyIngestion',
				NUX_PASSWORD: 'nux%PDDI@2021$',

				SMTP_HOST: 'ddcmail.mckesson.com',
				SMTP_PORT: '25',

				GCP_PROJECTID: 'gis-iam-prod-3d6b',
				GCP_KEYFILENAME:
					'C:/admin/rclone/gis-iam-prod-3d6b-46e5387733ff-PRD.json',
				GCP_BUCKETS: [
					{ name: 'Default', value: 'gfusw-pecm400-live' },
					{ name: 'Stage', value: 'gfusw-pecm402-stage' },
					{ name: 'MMS Archive', value: 'gfusw-pecm401-arch' },
					{ name: 'Packing Slip Archive', value: 'gfusw-pecm401-arch2' },
					{ name: 'General Archive', value: 'gfusw-pecm401-arch3' },
				],
			},
		},
		{
			name: 'directory-monitor-docorigin',
			script: './directory-monitor/directory-monitor-docorigin.js',
			watch: false,
			env: {
				NODE_ENV: 'PROD',
				NODE_APP_INSTANCE: 'PROD',
				DB_USER: 'svcecmnuxeo',
				DB_PASSWORD: '2DJCRIzlQFsnMZfzTRii3NXJ',
				DB_DATABASE: 'ecmtoolsdb',
				DB_SCHEMA: 'nuxeo',
				DB_PORT: '5432',
				DB_HOST: 'gfusw-pecm301-r0.na.corp.mckesson.com',
				DB_SSL_CA: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-server-ca.pem',
				DB_SSL_KEY: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-client-key.pem',
				DB_SSL_CERT: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-client-cert.pem',
				FP_ROOT: 'D:/DailyIngest',
				NUX_BASE_URL: 'https://ecm.mckesson.com/nuxeo/',
				NUX_USERNAME: 'svcDailyIngestion',
				NUX_PASSWORD: 'nux%PDDI@2021$',

				SMTP_HOST: 'ddcmail.mckesson.com',
				SMTP_PORT: '25',

				GCP_PROJECTID: 'gis-iam-prod-3d6b',
				GCP_KEYFILENAME:
					'C:/admin/rclone/gis-iam-prod-3d6b-46e5387733ff-PRD.json',
				GCP_BUCKETS: [
					{ name: 'Default', value: 'gfusw-pecm400-live' },
					{ name: 'Stage', value: 'gfusw-pecm402-stage' },
					{ name: 'MMS Archive', value: 'gfusw-pecm401-arch' },
					{ name: 'Packing Slip Archive', value: 'gfusw-pecm401-arch2' },
					{ name: 'General Archive', value: 'gfusw-pecm401-arch3' },
				],
			},
		},
		{
			name: 'directory-monitor-apwf',
			script: './directory-monitor/directory-monitor-apwf.js',
			watch: false,
			env: {
				NODE_ENV: 'PROD',
				NODE_APP_INSTANCE: 'PROD',
				DB_USER: 'svcecmnuxeo',
				DB_PASSWORD: '2DJCRIzlQFsnMZfzTRii3NXJ',
				DB_DATABASE: 'ecmtoolsdb',
				DB_SCHEMA: 'nuxeo',
				DB_PORT: '5432',
				DB_HOST: 'gfusw-pecm301-r0.na.corp.mckesson.com',
				DB_SSL_CA: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-server-ca.pem',
				DB_SSL_KEY: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-client-key.pem',
				DB_SSL_CERT: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-client-cert.pem',
				FP_ROOT: 'D:/DailyIngest',
				NUX_BASE_URL: 'https://ecm.mckesson.com/nuxeo/',
				NUX_USERNAME: 'svcDailyIngestion',
				NUX_PASSWORD: 'nux%PDDI@2021$',

				SMTP_HOST: 'ddcmail.mckesson.com',
				SMTP_PORT: '25',

				GCP_PROJECTID: 'gis-iam-prod-3d6b',
				GCP_KEYFILENAME:
					'C:/admin/rclone/gis-iam-prod-3d6b-46e5387733ff-PRD.json',
				GCP_BUCKETS: [
					{ name: 'Default', value: 'gfusw-pecm400-live' },
					{ name: 'Stage', value: 'gfusw-pecm402-stage' },
					{ name: 'MMS Archive', value: 'gfusw-pecm401-arch' },
					{ name: 'Packing Slip Archive', value: 'gfusw-pecm401-arch2' },
					{ name: 'General Archive', value: 'gfusw-pecm401-arch3' },
				],
			},
		},
		{
			name: 'directory-monitor-single',
			script: './directory-monitor/directory-monitor-single.js',
			watch: false,
			env: {
				NODE_ENV: 'PROD',
				NODE_APP_INSTANCE: 'PROD',
				DB_USER: 'svcecmnuxeo',
				DB_PASSWORD: '2DJCRIzlQFsnMZfzTRii3NXJ',
				DB_DATABASE: 'ecmtoolsdb',
				DB_SCHEMA: 'nuxeo',
				DB_PORT: '5432',
				DB_HOST: 'gfusw-pecm301-r0.na.corp.mckesson.com',
				DB_SSL_CA: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-server-ca.pem',
				DB_SSL_KEY: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-client-key.pem',
				DB_SSL_CERT: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-client-cert.pem',
				FP_ROOT: 'D:/DailyIngest',
				NUX_BASE_URL: 'https://ecm.mckesson.com/nuxeo/',
				NUX_USERNAME: 'svcDailyIngestion',
				NUX_PASSWORD: 'nux%PDDI@2021$',

				SMTP_HOST: 'ddcmail.mckesson.com',
				SMTP_PORT: '25',

				GCP_PROJECTID: 'gis-iam-prod-3d6b',
				GCP_KEYFILENAME:
					'C:/admin/rclone/gis-iam-prod-3d6b-46e5387733ff-PRD.json',
				GCP_BUCKETS: [
					{ name: 'Default', value: 'gfusw-pecm400-live' },
					{ name: 'Stage', value: 'gfusw-pecm402-stage' },
					{ name: 'MMS Archive', value: 'gfusw-pecm401-arch' },
					{ name: 'Packing Slip Archive', value: 'gfusw-pecm401-arch2' },
					{ name: 'General Archive', value: 'gfusw-pecm401-arch3' },
				],
			},
		},
		{
			name: 'audit-manager',
			script: './audit-manager/auditprocessors/bol-audit.js',
			watch: true,
			env: {
				NODE_ENV: 'PROD',
				NODE_APP_INSTANCE: 'PROD',
				DB_USER: 'svcecmnuxeo',
				DB_PASSWORD: '2DJCRIzlQFsnMZfzTRii3NXJ',
				DB_DATABASE: 'ecmtoolsdb',
				DB_SCHEMA: 'nuxeo',
				DB_PORT: '5432',
				DB_HOST: 'gfusw-pecm301-r0.na.corp.mckesson.com',
				DB_SSL_CA: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-server-ca.pem',
				DB_SSL_KEY: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-client-key.pem',
				DB_SSL_CERT: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-client-cert.pem',
				FP_ROOT: 'D:/DailyIngest',
				NUX_BASE_URL: 'https://ecm.mckesson.com/nuxeo/',
				NUX_USERNAME: 'svcDailyIngestion',
				NUX_PASSWORD: 'nux%PDDI@2021$',

				SMTP_HOST: 'ddcmail.mckesson.com',
				SMTP_PORT: '25',

				GCP_PROJECTID: 'gis-iam-prod-3d6b',
				GCP_KEYFILENAME:
					'C:/admin/rclone/gis-iam-prod-3d6b-46e5387733ff-PRD.json',
				GCP_BUCKETS: [
					{ name: 'Default', value: 'gfusw-pecm400-live' },
					{ name: 'Stage', value: 'gfusw-pecm402-stage' },
					{ name: 'MMS Archive', value: 'gfusw-pecm401-arch' },
					{ name: 'Packing Slip Archive', value: 'gfusw-pecm401-arch2' },
					{ name: 'General Archive', value: 'gfusw-pecm401-arch3' },
				],
			},
		},
		{
			name: 'move-bol',
			script: './tools/movebol.js',
			instances: 1,
      		exec_mode: 'fork',
      		cron_restart: "*/15 * * * *",
      		watch: false,
      		autorestart: false,
			env: {
				NODE_ENV: 'PROD',
				NODE_APP_INSTANCE: 'PROD',
				DB_USER: 'svcecmnuxeo',
				DB_PASSWORD: '2DJCRIzlQFsnMZfzTRii3NXJ',
				DB_DATABASE: 'ecmtoolsdb',
				DB_SCHEMA: 'nuxeo',
				DB_PORT: '5432',
				DB_HOST: 'gfusw-pecm301-r0.na.corp.mckesson.com',
				DB_SSL_CA: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-server-ca.pem',
				DB_SSL_KEY: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-client-key.pem',
				DB_SSL_CERT: 'C:/admin/certs/gfusw-pecm301-r0-pgsql-client-cert.pem',
				FP_ROOT: 'D:/DailyIngest',
				NUX_BASE_URL: 'https://ecm.mckesson.com/nuxeo/',
				NUX_USERNAME: 'svcDailyIngestion',
				NUX_PASSWORD: 'nux%PDDI@2021$',

				SMTP_HOST: 'ddcmail.mckesson.com',
				SMTP_PORT: '25',

				GCP_PROJECTID: 'gis-iam-prod-3d6b',
				GCP_KEYFILENAME:
					'C:/admin/rclone/gis-iam-prod-3d6b-46e5387733ff-PRD.json',
				GCP_BUCKETS: [
					{ name: 'Default', value: 'gfusw-pecm400-live' },
					{ name: 'Stage', value: 'gfusw-pecm402-stage' },
					{ name: 'MMS Archive', value: 'gfusw-pecm401-arch' },
					{ name: 'Packing Slip Archive', value: 'gfusw-pecm401-arch2' },
					{ name: 'General Archive', value: 'gfusw-pecm401-arch3' },
				],
			},
		},
	],
};
